# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello-docker:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello Docker!"
  build-docker:
    working_directory: /Users/tuyenpham/Desktop/Projects/TADP/Ductuyen861vn/WelcomeDockerForPrivateTest
    resource_class: arm.medium
    docker:
      - image: docker:24.0.5-git
        auth:
          username: ductuyen861vn
          password: Unlockok123
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Push docker image to dockerHUB
          command: |
            docker login --username ductuyen861vn --password Unlockok123
            docker build -t ductuyen861vn/welcomedockerforprivatetest .
            docker push ductuyen861vn/welcomedockerforprivatetest:latest
            docker run -p 8080:3000 ductuyen861vn/welcomedockerforprivatetest:latest
  run-container:
    working_directory: /Users/tuyenpham/Desktop/Projects/TADP/Ductuyen861vn/WelcomeDockerForPrivateTest
    resource_class: arm.medium
    docker:
      - image: docker:24.0.5-git
        auth:
          username: ductuyen861vn
          password: Unlockok123
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk update; apk add curl
      - run:
          name: Pull docker and run
          command: |
            docker login --username ductuyen861vn --password Unlockok123
            docker pull ductuyen861vn/welcomedockerforprivatetest:latest
            docker run -d --name welcomedockerforprivatetest -p 8080:3000 ductuyen861vn/welcomedockerforprivatetest:latest
            docker container ls
            curl welcomedockerforprivatetest:8080

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-docker-workflow:
    jobs:
      - run-container
      - say-hello-docker